feat(docker): Add healthcheck
tchiotludo/akhq pull request #1136
Opened 2022-07-03 12:51 UTC by ThomasSanson

2022-07-03 18:23 UTC, tchiotludo requested changes
Seems that there is a mistake on the url

2022-07-03 18:23 UTC, tchiotludo commented on Dockerfile
> +  CMD curl --fail http://localhost/8080 || exit 1
```suggestion
  CMD curl --fail http://localhost:8080/health || exit 1
```

2022-07-03 18:30 UTC, ThomasSanson commented on Dockerfile
> +  CMD curl --fail http://localhost/8080 || exit 1
indeed 😅

2022-07-03 18:47 UTC, merged

2022-11-28 06:53 UTC, sandropace commented
healthchecks are behind authentication.  that should be outside of auth, so that k8s can still verify health of the container running akhq.

2022-11-28 06:54 UTC, tchiotludo commented
No, healthcheck are on separated port with no auth