Feat/304 support references
tchiotludo/akhq pull request #408
Opened 2020-09-23 22:09 UTC by mredjem

Manage Avro schema references coming with Confluent schema registry 5.5.0:

- manage Avro schema references to read messages from topics
- manage Avro schema references to display schemas from the schema registry
- add possibility to register a schema with its type references in the UI (old way with only a json avro schema still compatible)

Register a schema with references:
```json
{
  "schema": "...",
  "references": [
    {
      "name": "Schema1",
      "subject": "schema_1",
      "version": 1
    }
  ]
}
```

Schema registry can now manage Protobuf and JSON, this change targets Avro only for now.

2020-09-30 19:44 UTC, tchiotludo requested changes
Seems to do the jobs (I think, I don't use reference for now).
Just seems strange that test work with wrong subject ?

2020-09-30 19:44 UTC, tchiotludo commented on src/test/java/org/akhq/repositories/SchemaRegistryRepositoryTest.java
> +    public final static String SUBJECT_4 = "SCHEMA_3";
```suggestion
    public final static String SUBJECT_4 = "SCHEMA_4";
```

2020-09-30 19:48 UTC, tchiotludo commented
also seems to break the old way to register schema : 

![image](https://user-images.githubusercontent.com/2064609/94732449-9538b080-0366-11eb-8521-c5948e1abc8e.png)

I only put the `SCHEMA_3` and I was unable to register the schema

2020-10-02 12:03 UTC, mredjem commented
Fixed issue with the schema registering and the unit test.

2020-10-02 20:06 UTC, merged

2020-10-02 20:07 UTC, tchiotludo commented
Seems to be work now !! 

Thanks :+1: