kafka-connect-sorting-filtering
tchiotludo/akhq pull request #602
Opened 2021-02-14 15:16 UTC by PLarboulette

Hello, 

First PR on this repository to add a search bar in the Kafka Connect list. 

I use as an example the Schema Registry screen and implementation.

2021-02-14 15:21 UTC, PLarboulette commented on src/main/java/org/akhq/controllers/TopicController.java
> +import org.akhq.models.Record;
I have compilation problems here, with ambiguous usage of Record (java.lang.Record and Record of package models). I import it explicitly.

2021-02-14 15:21 UTC, PLarboulette commented on src/test/java/org/akhq/controllers/TopicControllerTest.java
> +import org.akhq.models.Record;
I have compilation problems here, with ambiguous usage of Record (java.lang.Record and Record of package models). I import it explicitly.

2021-02-14 17:09 UTC, PLarboulette commented
I have some problems with the "GroupControllerTest", function listApi() line 42 (expected: <1> but was: <5>) 
I can't understand why, I think I don't touch this part and this fail doesn't seem to be a problem for the global build.

2021-02-14 19:42 UTC, tchiotludo commented
@PLarboulette : some test are flaky ;)
Last one works as you see !
Thanks for this one, will look at this soon ;)

2021-03-07 19:38 UTC, tchiotludo reviewed
Hi @PLarboulette 
Sorry for late response, really busy here ! 
I have made some test; the search is working fine :+1: 
But the pagination seems to be not working, the total page is not displayed, and changing to next page just keep the same result than previous one. 

Can you look at this ?

2021-03-07 19:38 UTC, tchiotludo requested changes
See comment above

2021-03-08 20:56 UTC, PLarboulette commented
Hello, 

Oh sorry, It's pushed with a fix, I think it's better. 

FYI, during my work in Kafka Connect, I find a similar to mine : https://github.com/tchiotludo/akhq/pull/622

2021-03-09 21:20 UTC, merged